- name: Install Helm (if missing)
  shell: |
    set -e
    if ! command -v helm >/dev/null 2>&1; then
      curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    fi
  args:
    creates: /usr/local/bin/helm

- name: Create monitoring namespace
  command: kubectl create namespace monitoring
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: ns_out
  failed_when: ns_out.rc != 0 and ("AlreadyExists" not in ns_out.stderr)
  changed_when: ns_out.rc == 0

- name: Add Prometheus Community Helm repo
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  changed_when: false

- name: Update Helm repos
  command: helm repo update
  changed_when: false

- name: Install/upgrade kube-prometheus-stack
  command: >
    helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack
    --namespace monitoring
    --version {{ kps_chart_version | default('81.5.1') }}
    --set prometheus.prometheusSpec.retention=6h
    --set grafana.adminPassword=admin
    --set grafana.grafana\\.ini.server.root_url=%(protocol)s://%(domain)s/{{ grafana_path }}
    --set grafana.grafana\\.ini.server.serve_from_sub_path=true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true
