- name: Install containerd
  apt:
    update_cache: true
    name:
      - containerd
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate default containerd config if missing
  command: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Write containerd config.toml
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_config.stdout }}"
    mode: "0644"

- name: Set SystemdCgroup = true
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart and enable containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true
