apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-topics
  namespace: argocd
spec:
  project: data-pipeline
  source:
    repoURL: https://github.com/network-telemetry-pipeline/data-pipeline.git
    targetRevision: main
    path: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-bronze
  namespace: argocd
spec:
  project: data-pipeline
  source:
    repoURL: https://github.com/network-telemetry-pipeline/data-pipeline.git
    targetRevision: main
    path: spark/bronze
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-gold
  namespace: argocd
spec:
  project: data-pipeline
  source:
    repoURL: https://github.com/network-telemetry-pipeline/data-pipeline.git
    targetRevision: main
    path: spark/gold
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-api
  namespace: argocd
spec:
  project: data-pipeline
  source:
    repoURL: https://github.com/network-telemetry-pipeline/data-pipeline.git
    targetRevision: main
    path: dashboard-api
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
