- name: Prepare argocd ingress
  copy:
    dest: /tmp/argocd-ingress.yaml
    content: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: argocd
        namespace: argocd
        annotations:
          cert-manager.io/cluster-issuer: {{ cluster_issuer_name }}
      spec:
        ingressClassName: nginx
        tls:
        - hosts:
          - {{ platform_domain }}
          secretName: argocd-tls
        rules:
        - host: {{ platform_domain }}
          http:
            paths:
            - path: /{{ argocd_path }}
              pathType: Prefix
              backend:
                service:
                  name: argo-cd-argocd-server
                  port:
                    number: 80
  changed_when: false

- name: Apply argocd ingress
  command: kubectl apply -f /tmp/argocd-ingress.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

- name: Prepare grafana ingress
  copy:
    dest: /tmp/grafana-ingress.yaml
    content: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana
        namespace: monitoring
        annotations:
          cert-manager.io/cluster-issuer: {{ cluster_issuer_name }}
      spec:
        ingressClassName: nginx
        tls:
        - hosts:
          - {{ platform_domain }}
          secretName: grafana-tls
        rules:
        - host: {{ platform_domain }}
          http:
            paths:
            - path: /grafana
              pathType: Prefix
              backend:
                service:
                  name: kube-prometheus-stack-grafana
                  port:
                    number: 80
  changed_when: false

- name: Apply grafana ingress
  command: kubectl apply -f /tmp/grafana-ingress.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true
